import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _values = {
    'ar': {
      'appTitle': 'رسالة الإسلام',
      'settings': 'الإعدادات',
      'appLanguage': 'لغة التطبيق',
      'contentLanguage': 'لغة المحتوى',
      'drawer_continue': 'متابعة القراءة',
      'drawer_bookmarks': 'العلامات المرجعية',
      'drawer_downloads': 'التنزيلات',
      'drawer_sync': 'تحديث المحتوى',
      'drawer_syncing': 'جاري التحديث...',
      'drawer_about': 'حول',
      'drawer_privacy': 'الخصوصية',
      'drawer_contact': 'تواصل مع داعية',
      'drawer_share': 'مشاركة',
      'drawer_rate': 'تقييم',
      'drawer_dark_mode': 'الوضع الداكن',
      'drawer_light_mode': 'الوضع الفاتح',
      'about_app_header': 'عن التطبيق',
      'about_app_name': 'رسالة الإسلام',
      'about_legalese': 'جميع الحقوق محفوظة © 2025',
      'ready_offline': 'جاهز للعمل دون إنترنت',
      'version': 'الإصدار',
      'dialog_language': 'اختر اللغة',
      'dialog_privacy': 'سياسة الخصوصية',
      'privacy_policy_content':
          'سياسة الخصوصية لهذا التطبيق بسيطة:\n\n1. نحن لا نجمع أي بيانات شخصية.\n2. جميع البيانات (مثل العلامات المرجعية) تخزن محلياً على جهازك.\n3. التطبيق لا يشارك أي معلومات مع أطراف ثالثة.\n\nإذا كان لديك أي استفسار، يرجى التواصل معنا.',
      'dialog_ok': 'موافق',
      'sync_success': 'تم تحديث المحتوى بنجاح',
      'sync_fail': 'فشل التحديث',
      'theme_switched': 'تم تغيير النمط',
      'lang_switched': 'تم تغيير اللغة إلى',
      'no_read_history': 'لا يوجد سجل قراءة سابق',
      'no_sections': 'لا توجد أقسام بعد',
      'loading_error': 'حدث خطأ في التحميل',
      'retry': 'إعادة المحاولة',
      'no_content': 'لا محتوى',
      'all': 'الكل',
      'empty_section': 'لا يوجد محتوى في هذا القسم',
      'no_translation': 'لا توجد ترجمة للقراءة',
      'declare_islam': 'إعلان الإسلام',
      'islam_step': 'خطوة مباركة نحو النور',
      'contact_daiyah': 'تواصل مع داعية',
      'daiyah_desc': 'نحن هنا للإجابة على أسئلتك',
      'content_header': 'المحتوى',
      'bookmark_saved': 'تم حفظ الموضع',
      'flip_page_hint': 'اقلب الصفحة لقراءة المزيد',
      'scroll_hint': 'اسحب لأسفل للقراءة',
      'back': 'رجوع',
      'no_bookmarks_hint':
          'لا توجد مذكرات محفوظة حتى الآن\nأضف واحدة من صفحة القراءة',
      'bookmarks_title': 'المذكرات',
      'bookmark_deleted': 'تم حذف المذكرة',
      'bookmark_default_title': 'مذكرة',
      'time_now': 'الآن',
      'time_min_ago': 'قبل {0} دقيقة',
      'time_hour_ago': 'قبل {0} ساعة',
      'time_day_ago': 'قبل {0} يوم',
      'chapters_title': 'الفهرس',
      'appearance_title': 'مظهر القراءة',
      'view_scroll': 'تمرير',
      'view_pager': 'صفحات',
      'text_settings': 'النص',
      'font_size': 'حجم الخط',
      'line_height': 'تباعد الأسطر',
      'language_settings': 'اللغة',
      'downloads_title': 'التنزيلات',
      'generic_error': 'حدث خطأ: {0}',
      'no_downloads': 'لا توجد ملفات صوتية منزلة',
      'message_default_title': 'رسالة #{0}',
      'delete_file_title': 'حذف الملف؟',
      'delete_file_confirmation': 'هل تريد حذف الملف الصوتي لـ "{0}"؟',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'deleted_success': 'تم الحذف',
      'contact_daiyah_title': 'تواصل مع داعية',
      'we_here_help': 'نحن هنا لمساعدتك',
      'contact_desc':
          'يمكنك التواصل معنا عبر الواتساب أو البريد الإلكتروني لطرح أي سؤال أو استفسار.\n\nتنبيه: يتم الرد حسب التوفر، نسعى للرد في أقرب وقت ممكن.',
      'whatsapp': 'واتساب',
      'whatsapp_subtitle': 'تواصل مباشر عبر الرسائل',
      'email': 'البريد الإلكتروني',
      'email_subtitle': 'أرسل لنا استفسارك مفصلاً',
      'launch_error': 'تعذر فتح الرابط: {0}',
      'data_error': 'خطأ في البيانات: {0}',
      'welcome_header': 'أهلاً بك...',
      'islam_definition':
          'الإسلام هو الاستسلام لله بالتوحيد والانقياد له بالطاعة.\nلا يتطلب الدخول في الإسلام أي إجراءات رسمية، فقط النطق بالشهادتين بقلب موقن.',
      'shahada_arabic': 'أشهد أن لا إله إلا الله\nوأشهد أن محمداً رسول الله',
      'shahada_english':
          'I bear witness that there is no god but Allah,\nand I bear witness that Muhammad is the Messenger of Allah.',
      'declare_button': 'أُعلن دخولي في الإسلام',
      'declare_disclaimer':
          'هذا الزر لا يقوم بتسجيل أي بيانات، هو مجرد إعلان شخصي منك.',
      'congrats_header': 'مبارك عليك!',
      'congrats_body':
          'لقد خطوت الخطوة الأهم في حياتك.\nنسأل الله أن يثبتك وينير قلبك.',
      'whats_next': 'ماذا بعد؟',
      'next_step_1': 'ابدأ بتعلم الصلاة',
      'next_step_2': 'اقرأ القرآن وتدبر معانيه',
      'next_step_3': 'تواصل معنا لأي استفسار',
      'messages_load_error': 'حدث خطأ في تحميل الرسائل.\n{0}',
      'no_global_bookmarks': 'لا توجد علامات مرجعية حتى الآن',
      'no_bookmarks_found': 'لا توجد علامات مرجعية لرسائل موجودة',
      'default_excerpt': 'نص مقتبس',
      'audio_language_label': 'لغة الصوت:',
      'audio_loading_error': 'خطأ في تحميل الصوت: {0}',
      'changing_language_audio': 'جاري تغيير اللغة وتشغيل الصوت...',
      'audio_download_error': 'تعذر تحميل الصوت',
      'speed_label': 'السرعة\n{0}x',
      'download_button': 'تنزيل',
      'file_already_downloaded': 'الملف محمل مسبقاً',
      'downloading_progress': 'جاري التنزيل...',
      'download_completed': 'تم التنزيل',
      'download_failed': 'فشل التنزيل: {0}',
      'no_audio_source': 'لا يوجد مصدر صوتي',
      'audio_playback_error': 'فشل تشغيل الصوت: {0}',
      'local_audio_error': 'فشل تشغيل الملف المحلي: {0}',
      'select_content_language': 'اختر لغة المحتوى',
      'content_language_desc': 'يمكنك قراءة واستماع الرسائل بلغات متعددة',
      'confirm_continue': 'تأكيد واستمرار',
      'change_language_anytime': 'يمكنك تغيير اللغة في أي وقت من داخل كل رسالة',
      'section_meaning': 'الغاية من الوجود',
      'section_islam': 'التعريف بالإسلام',
      'section_logic': 'حوارات عقلية',
      'section_god': 'معرفة الله',
      'section_prophet': 'النبي محمد ﷺ',
      'section_quran': 'عن القرآن الكريم',
      'section_ready': 'مستعد للإسلام',
      'section_guidance': 'دليل المسلم الجديد',
      'read': 'قراءة',
      'listen': 'استماع',
      'lang_ar': 'العربية',
      'lang_en': 'الإنجليزية',
      'lang_fr': 'الفرنسية',
      'lang_ur': 'الأردية',
      'lang_fa': 'الفارسية',
      'lang_id': 'الإندونيسية',
      'lang_sw': 'السواحيلية',
      'lang_am': 'الأمهرية',
      'lang_hi': 'الهندية',
      'lang_tl': 'التاغالوغية',
      'lang_bn': 'البنغالية',
      'lang_tr': 'التركية',
      'lang_ru': 'الروسية',
      'lang_zh': 'الصينية',
      'lang_es': 'الإسبانية',
      'lang_pt': 'البرتغالية',
      'lang_de': 'الألمانية',
      'onboarding_welcome_title': 'أهلاً بك في "رسالة الإسلام"',
      'onboarding_welcome_desc':
          'اكتشف الغاية من الوجود من خلال محتوى روحي وموجه بعناية.',
      'onboarding_language_title': 'محتوى متعدد اللغات',
      'onboarding_language_desc':
          'تصفح واستمع للمحتوى بلغات متعددة تشمل العربية والإنجليزية والفرنسية.',
      'onboarding_audio_title': 'تجربة صوتية',
      'onboarding_audio_desc':
          'استمع للمقالات والتوجيهات بصوت نقي عبر المشغل المدمج.',
      'onboarding_get_started': 'ابدأ الآن',
      'onboarding_skip': 'تخطي',
    },
    'en': {
      'appTitle': 'Message of Islam',
      'settings': 'Settings',
      'appLanguage': 'App Language',
      'contentLanguage': 'Content Language',
      'drawer_continue': 'Continue Reading',
      'drawer_bookmarks': 'Bookmarks',
      'drawer_downloads': 'Downloads',
      'drawer_sync': 'Update Content',
      'drawer_syncing': 'Updating...',
      'drawer_about': 'About',
      'drawer_privacy': 'Privacy Policy',
      'drawer_contact': 'Contact Us',
      'drawer_share': 'Share App',
      'drawer_rate': 'Rate App',
      'drawer_dark_mode': 'Dark Mode',
      'drawer_light_mode': 'Light Mode',
      'about_app_header': 'About App',
      'about_app_name': 'Message of Islam',
      'about_legalese': 'All rights reserved © 2025',
      'ready_offline': 'Works Offline',
      'version': 'Version',
      'dialog_language': 'Choose Language',
      'dialog_privacy': 'Privacy Policy',
      'privacy_policy_content':
          'The privacy policy for this app is simple:\n\n1. We do not collect any personal data.\n2. All data (like bookmarks) is stored locally on your device.\n3. The app does not share any information with third parties.\n\nIf you have any questions, please contact us.',
      'dialog_ok': 'OK',
      'sync_success': 'Content Updated Successfully',
      'sync_fail': 'Update Failed',
      'theme_switched': 'Theme Changed',
      'lang_switched': 'Language Changed to',
      'no_read_history': 'No reading history found',
      'no_sections': 'No sections found',
      'loading_error': 'Error loading content',
      'retry': 'Retry',
      'no_content': 'No content',
      'all': 'All',
      'empty_section': 'No content in this section',
      'no_translation': 'No translation available',
      'declare_islam': 'Declare Islam',
      'islam_step': 'A blessed step towards the light',
      'contact_daiyah': 'Contact a Daiyah',
      'daiyah_desc': 'We are here to answer your questions',
      'content_header': 'Content',
      'bookmark_saved': 'Position saved',
      'flip_page_hint': 'Flip page to read more',
      'scroll_hint': 'Swipe down to read',
      'back': 'Back',
      'chapter': 'Chapter',
      'no_bookmarks_hint':
          'No bookmarks saved yet\nAdd one from the reading page',
      'bookmarks_title': 'Bookmarks',
      'bookmark_deleted': 'Bookmark deleted',
      'bookmark_default_title': 'Bookmark',
      'time_now': 'Just now',
      'time_min_ago': '{0}m ago',
      'time_hour_ago': '{0}h ago',
      'time_day_ago': '{0}d ago',
      'chapters_title': 'Chapters',
      'appearance_title': 'Appearance',
      'view_scroll': 'Scroll',
      'view_pager': 'Paged',
      'text_settings': 'Text',
      'font_size': 'Font Size',
      'line_height': 'Line Spacing',
      'language_settings': 'Language',
      'downloads_title': 'Downloads',
      'generic_error': 'Error: {0}',
      'no_downloads': 'No downloaded audio files',
      'message_default_title': 'Message #{0}',
      'delete_file_title': 'Delete File?',
      'delete_file_confirmation': 'Delete audio file for "{0}"?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'deleted_success': 'Deleted successfully',
      'contact_daiyah_title': 'Contact Daiyah',
      'we_here_help': 'We are here to help',
      'contact_desc':
          'You can contact us via WhatsApp or Email for any questions.\n\nNote: We reply based on availability and strive to respond as soon as possible.',
      'whatsapp': 'WhatsApp',
      'whatsapp_subtitle': 'Direct message chat',
      'email': 'Email',
      'email_subtitle': 'Send us a detailed inquiry',
      'launch_error': 'Could not launch: {0}',
      'data_error': 'Data error: {0}',
      'welcome_header': 'Welcome...',
      'islam_definition':
          'Islam is submission to God through Monotheism and obedience.\nEntering Islam does not require any formal procedures, only pronouncing the Testimony of Faith with a convinced heart.',
      'shahada_arabic': 'أشهد أن لا إله إلا الله\nوأشهد أن محمداً رسول الله',
      'shahada_english':
          'I bear witness that there is no god but Allah,\nand I bear witness that Muhammad is the Messenger of Allah.',
      'declare_button': 'I declare entering Islam',
      'declare_disclaimer':
          'This button does not record any data, it is just a personal declaration from you.',
      'congrats_header': 'Congratulations!',
      'congrats_body':
          'You have taken the most important step in your life.\nWe ask God to strengthen you and enlighten your heart.',
      'whats_next': 'What\'s next?',
      'next_step_1': 'Start learning Prayer',
      'next_step_2': 'Read the Quran and contemplate its meanings',
      'next_step_3': 'Contact us for any questions',
      'messages_load_error': 'Error loading messages.\n{0}',
      'no_global_bookmarks': 'No bookmarks yet',
      'no_bookmarks_found': 'No bookmarks found for existing messages',
      'default_excerpt': 'Excerpt',
      'audio_language_label': 'Audio Language:',
      'audio_loading_error': 'Error loading audio: {0}',
      'changing_language_audio': 'Changing language and playing audio...',
      'audio_download_error': 'Could not load audio',
      'speed_label': 'Speed\n{0}x',
      'download_button': 'Download',
      'file_already_downloaded': 'File already downloaded',
      'downloading_progress': 'Downloading...',
      'download_completed': 'Download completed',
      'download_failed': 'Download failed: {0}',
      'no_audio_source': 'No audio source',
      'audio_playback_error': 'Audio playback failed: {0}',
      'local_audio_error': 'Failed to play local file: {0}',
      'select_content_language': 'Select Content Language',
      'content_language_desc':
          'You can read and listen to messages in multiple languages',
      'confirm_continue': 'Confirm & Continue',
      'change_language_anytime':
          'You can change the language anytime from within each message',
      'section_meaning': 'The Purpose of Existence',
      'section_islam': 'Introduction to Islam',
      'section_logic': 'Logical Dialogues',
      'section_god': 'Knowing Allah',
      'section_prophet': 'Prophet Muhammad PBUH',
      'section_quran': 'About the Holy Quran',
      'section_ready': 'Ready for Islam',
      'section_guidance': 'New Muslim Guide',
      'read': 'Read',
      'listen': 'Listen',
      'lang_ar': 'Arabic',
      'lang_en': 'English',
      'lang_fr': 'French',
      'lang_ur': 'Urdu',
      'lang_fa': 'Persian',
      'lang_id': 'Indonesian',
      'lang_sw': 'Swahili',
      'lang_am': 'Amharic',
      'lang_hi': 'Hindi',
      'lang_tl': 'Tagalog',
      'lang_bn': 'Bengali',
      'lang_tr': 'Turkish',
      'lang_ru': 'Russian',
      'lang_zh': 'Chinese',
      'lang_es': 'Spanish',
      'lang_pt': 'Portuguese',
      'lang_de': 'German',
      'onboarding_welcome_title': 'Welcome to Alghaya',
      'onboarding_welcome_desc':
          'Discover the purpose of creation through curated content and spiritual guidance.',
      'onboarding_language_title': 'Multilingual Content',
      'onboarding_language_desc':
          'Access content in multiple languages including Arabic, English, and French.',
      'onboarding_audio_title': 'Audio Experience',
      'onboarding_audio_desc':
          'Listen to articles and guidance with our integrated audio player.',
      'onboarding_get_started': 'Get Started',
      'onboarding_skip': 'Skip',
    },
  };

  static String of(BuildContext context, String key) {
    // If context is not available or localizations not fully set up, fallback safely
    try {
      final locale = Localizations.localeOf(context);
      return _values[locale.languageCode]?[key] ?? _values['ar']![key] ?? key;
    } catch (_) {
      return _values['ar']![key] ?? key;
    }
  }

  // Helper for non-context usage if needed (using code directly)
  static String get(String code, String key) {
    return _values[code]?[key] ?? _values['ar']![key] ?? key;
  }
}
