import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _values = {
    'ar': {
      'appTitle': 'رسالة الإسلام',
      'settings': 'الإعدادات',
      'appLanguage': 'لغة التطبيق',
      'contentLanguage': 'لغة المحتوى',
      'drawer_continue': 'متابعة القراءة',
      'drawer_bookmarks': 'العلامات المرجعية',
      'drawer_sync': 'تحديث المحتوى',
      'drawer_syncing': 'جاري التحديث...',
      'drawer_about': 'حول',
      'drawer_privacy': 'الخصوصية',
      'drawer_contact': 'تواصل مع داعية',
      'drawer_share': 'مشاركة',
      'drawer_rate': 'تقييم',
      'drawer_dark_mode': 'الوضع الداكن',
      'drawer_light_mode': 'الوضع الفاتح',
      'theme_system': 'مظهر النظام',
      'dark_mode_subtitle': 'تغيير مظهر التطبيق',
      'settings_label': 'إعدادات الصوت',
      'quick_actions_header': 'الإجراءات السريعة',
      'about_app_header': 'عن التطبيق',
      'about_app_name': 'رسالة الإسلام',
      'about_legalese': 'جميع الحقوق محفوظة © 2025',
      'ready_offline': 'جاهز للعمل دون إنترنت',
      'version': 'الإصدار',
      'dialog_language': 'اختر اللغة',
      'dialog_privacy': 'سياسة الخصوصية',
      'privacy_policy_content':
          'سياسة الخصوصية لهذا التطبيق بسيطة:\n\n1. نحن لا نجمع أي بيانات شخصية.\n2. جميع البيانات (مثل العلامات المرجعية) تخزن محلياً على جهازك.\n3. التطبيق لا يشارك أي معلومات مع أطراف ثالثة.\n\nإذا كان لديك أي استفسار، يرجى التواصل معنا.',
      'dialog_ok': 'موافق',
      'sync_success': 'تم تحديث المحتوى بنجاح',
      'sync_fail': 'فشل التحديث',
      'theme_switched': 'تم تغيير النمط',
      'lang_switched': 'تم تغيير اللغة إلى',
      'no_read_history': 'لا يوجد سجل قراءة سابق',
      'no_sections': 'لا توجد أقسام بعد',
      'loading_error': 'حدث خطأ في التحميل',
      'retry': 'إعادة المحاولة',
      'no_content': 'لا محتوى',
      'all': 'الكل',
      'empty_section': 'لا يوجد محتوى في هذا القسم',
      'no_translation': 'لا توجد ترجمة للقراءة',
      'declare_islam': 'إعلان الإسلام',
      'islam_step': 'خطوة مباركة نحو النور',
      'contact_daiyah': 'تواصل مع داعية',
      'daiyah_desc': 'نحن هنا للإجابة على أسئلتك',
      'content_header': 'المحتوى',
      'bookmark_saved': 'تم حفظ الموضع',
      'flip_page_hint': 'اقلب الصفحة لقراءة المزيد',
      'scroll_hint': 'اسحب لأسفل للقراءة',
      'back': 'رجوع',
      'no_bookmarks_hint':
          'لا توجد مذكرات محفوظة حتى الآن\nأضف واحدة من صفحة القراءة',
      'bookmarks_title': 'المذكرات',
      'bookmark_deleted': 'تم حذف المذكرة',
      'bookmark_default_title': 'مذكرة',
      'time_now': 'الآن',
      'time_min_ago': 'قبل {0} دقيقة',
      'time_hour_ago': 'قبل {0} ساعة',
      'time_day_ago': 'قبل {0} يوم',
      'chapters_title': 'الفهرس',
      'appearance_title': 'مظهر القراءة',
      'view_scroll': 'تمرير',
      'view_pager': 'صفحات',
      'text_settings': 'النص',
      'font_size': 'حجم الخط',
      'line_height': 'تباعد الأسطر',
      'language_settings': 'اللغة',
      'default_content_language': 'لغة المحتوى الافتراضية',
      'not_set': 'غير محددة',
      'use_default_language': 'استخدام اللغة الافتراضية',
      'language_picker_title': 'اختر لغة هذه المادة',
      'language_picker_subtitle': 'سيتم تطبيق اللغة على هذه الرسالة فقط',
      'custom_override_badge': 'مخصص',
      'default_label': 'الافتراضية',
      'generic_error': 'حدث خطأ: {0}',
      'message_default_title': 'رسالة #{0}',
      'delete_file_title': 'حذف الملف؟',
      'delete_file_confirmation': 'هل تريد حذف الملف الصوتي لـ "{0}"؟',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'deleted_success': 'تم الحذف',
      'contact_daiyah_title': 'تواصل مع داعية',
      'we_here_help': 'نحن هنا لمساعدتك',
      'contact_desc':
          'يمكنك التواصل معنا عبر الواتساب أو البريد الإلكتروني لطرح أي سؤال أو استفسار.\n\nتنبيه: يتم الرد حسب التوفر، نسعى للرد في أقرب وقت ممكن.',
      'whatsapp': 'واتساب',
      'whatsapp_subtitle': 'تواصل مباشر عبر الرسائل',
      'email': 'البريد الإلكتروني',
      'email_subtitle': 'أرسل لنا استفسارك مفصلاً',
      'launch_error': 'تعذر فتح الرابط: {0}',
      'data_error': 'خطأ في البيانات: {0}',
      'welcome_header': 'أهلاً بك...',
      'islam_definition':
          'الإسلام هو الاستسلام لله بالتوحيد والانقياد له بالطاعة.\nلا يتطلب الدخول في الإسلام أي إجراءات رسمية، فقط النطق بالشهادتين بقلب موقن.',
      'shahada_arabic': 'أشهد أن لا إله إلا الله\nوأشهد أن محمداً رسول الله',
      'shahada_english':
          'I bear witness that there is no god but Allah,\nand I bear witness that Muhammad is the Messenger of Allah.',
      'declare_button': 'أُعلن دخولي في الإسلام',
      'declare_disclaimer':
          'هذا الزر لا يقوم بتسجيل أي بيانات، هو مجرد إعلان شخصي منك.',
      'congrats_header': 'مبارك عليك!',
      'congrats_body':
          'لقد خطوت الخطوة الأهم في حياتك.\nنسأل الله أن يثبتك وينير قلبك.',
      'whats_next': 'ماذا بعد؟',
      'next_step_1': 'ابدأ بتعلم الصلاة',
      'next_step_2': 'اقرأ القرآن وتدبر معانيه',
      'next_step_3': 'تواصل معنا لأي استفسار',
      'messages_load_error': 'حدث خطأ في تحميل الرسائل.\n{0}',
      'no_global_bookmarks': 'لا توجد علامات مرجعية حتى الآن',
      'no_bookmarks_found': 'لا توجد علامات مرجعية لرسائل موجودة',
      'default_excerpt': 'نص مقتبس',
      'audio_language_label': 'لغة الصوت:',
      'audio_loading_error': 'خطأ في تحميل الصوت: {0}',
      'changing_language_audio': 'جاري تغيير اللغة وتشغيل الصوت...',
      'audio_download_error': 'تعذر تحميل الصوت',
      'speed_label': 'السرعة\n{0}x',
      'download_button': 'تنزيل',
      'file_already_downloaded': 'الملف محمل مسبقاً',
      'downloading_progress': 'جاري التنزيل...',
      'download_completed': 'تم التنزيل',
      'download_failed': 'فشل التنزيل: {0}',
      'no_audio_source': 'لا يوجد مصدر صوتي',
      'audio_playback_error': 'فشل تشغيل الصوت',
      'local_audio_error': 'فشل تشغيل الملف المحلي: {0}',
      'select_content_language': 'اختر لغة المحتوى',
      'content_language_desc': 'يمكنك قراءة واستماع الرسائل بلغات متعددة',
      'confirm_continue': 'تأكيد واستمرار',
      'change_language_anytime': 'يمكنك تغيير اللغة في أي وقت من داخل كل رسالة',
      'section_meaning': 'الغاية من الوجود',
      'section_islam': 'التعريف بالإسلام',
      'section_logic': 'حوارات عقلية',
      'section_god': 'معرفة الله',
      'section_prophet': 'النبي محمد ﷺ',
      'section_quran': 'عن القرآن الكريم',
      'section_ready': 'مستعد للإسلام',
      'section_guidance': 'دليل المسلم الجديد',
      'read': 'قراءة',
      'listen': 'استماع',
      'lang_ar': 'العربية',
      'lang_en': 'الإنجليزية',
      'lang_fr': 'الفرنسية',
      'lang_ur': 'الأردية',
      'lang_fa': 'الفارسية',
      'lang_id': 'الإندونيسية',
      'lang_sw': 'السواحيلية',
      'lang_am': 'الأمهرية',
      'lang_hi': 'الهندية',
      'lang_tl': 'التاغالوغية',
      'lang_bn': 'البنغالية',
      'lang_tr': 'التركية',
      'lang_ru': 'الروسية',
      'lang_zh': 'الصينية',
      'lang_es': 'الإسبانية',
      'lang_pt': 'البرتغالية',
      'lang_de': 'الألمانية',
      'lang_ja': 'اليابانية',
      'lang_ko': 'الكورية',
      'lang_it': 'الإيطالية',
      'lang_nl': 'الهولندية',
      'lang_pl': 'البولندية',
      'lang_vi': 'الفيتنامية',
      'lang_th': 'التايلاندية',
      'lang_ms': 'الماليزية',
      'lang_he': 'العبرية',
      'lang_el': 'اليونانية',
      'lang_cs': 'التشيكية',
      'lang_ro': 'الرومانية',
      'lang_hu': 'المجرية',
      'select_language': 'اختر اللغة',
      'search_language': 'ابحث عن لغة...',
      'no_language_found': 'لم يتم العثور على لغة',
      // Contact Us
      'contact_us_title': 'تواصل معنا',
      'contact_us_subtitle': 'نحن هنا لمساعدتك',
      'contact_us_description': 'شاركنا أسئلتك، اقتراحاتك، أو أي مشكلة تواجهها',
      'contact_category': 'نوع الرسالة',
      'contact_message': 'رسالتك',
      'contact_message_hint': 'اكتب رسالتك هنا...',
      'contact_message_required': 'الرجاء كتابة رسالة',
      'contact_message_too_short': 'الرسالة قصيرة جداً (10 أحرف على الأقل)',
      'contact_email': 'البريد الإلكتروني',
      'contact_email_hint': 'للمتابعة معك',
      'contact_email_invalid': 'البريد الإلكتروني غير صالح',
      'contact_submit': 'إرسال',
      'contact_disclaimer': 'سنرد عليك في أقرب وقت ممكن. شكراً لتواصلك معنا!',
      'contact_sent_success': 'تم إرسال رسالتك بنجاح',
      'contact_saved_offline': 'تم حفظ رسالتك وسيتم إرسالها عند الاتصال',
      'optional': 'اختياري',
      'category_question': 'سؤال',
      'category_feedback': 'اقتراح أو ملاحظة',
      'category_bug_report': 'مشكلة تقنية',
      'category_feature_request': 'طلب ميزة',
      'category_other': 'أخرى',
      // Content Reporting
      'report_content_title': 'الإبلاغ عن مشكلة',
      'report_content_subtitle': 'ساعدنا في تحسين جودة المحتوى',
      'report_type': 'نوع المشكلة',
      'report_comment': 'تفاصيل إضافية',
      'report_comment_hint': 'يمكنك إضافة تفاصيل...',
      'report_submit': 'إرسال البلاغ',
      'report_info': 'سيتم إرسال معلومات الرسالة واللغة تلقائياً',
      'report_sent_success': 'تم إرسال البلاغ بنجاح',
      'report_saved_offline': 'تم حفظ البلاغ وسيتم إرساله عند الاتصال',
      'report_translation_error': 'خطأ في الترجمة',
      'report_missing_audio': 'الصوت غير متوفر',
      'report_technical_issue': 'مشكلة تقنية',
      'report_inappropriate_content': 'محتوى غير مناسب',
      'report_other': 'أخرى',
      'onboarding_welcome_title': 'مرحبًا بك في رسالة الإسلام',
      'onboarding_welcome_desc': 'مواد مختارة للتعريف بالإسلام: قراءة واستماع.',
      'onboarding_language_title': 'محتوى بعدة لغات',
      'onboarding_language_desc': 'اختر لغة كل مادة بسهولة.',
      'onboarding_audio_title': 'تجربة قراءة مريحة',
      'onboarding_audio_desc':
          'تحكم بحجم الخط وتباعد الأسطر ووضع القراءة المريح.',
      'onboarding_get_started': 'ابدأ الآن',
      'onboarding_next': 'التالي',
      'onboarding_skip': 'تخطي',
      'onboarding_previous': 'السابق',
      'onboarding_step_counter': '{current}/{total}',
      'listen_action': 'استماع',
      'audio_unavailable_label': 'الصوت غير متوفر لهذه اللغة',
      'change_language_action': 'تغيير اللغة',
      'audio_next_track': 'التالي',
      'audio_previous_track': 'السابق',
      'audio_loading_progress': 'جاري تحميل الصوت...',
      'audio_play_button': 'تشغيل {0}',
      'audio_pause_button': 'إيقاف مؤقت',
      'audio_loading': 'جاري التحميل',
      'audio_speed_control': 'التحكم في السرعة، الحالي {0}',
      // Declare Islam Feature
      'di_intro_meaning_title': 'معنى الشهادتين',
      'di_intro_meaning_body':
          'هي مفتاح الإسلام: أن تشهد أن لا إله إلا الله وأن محمداً رسول الله.',
      'di_intro_note_title': 'تنبيه هام',
      'di_intro_note_body':
          'هذه خطوة شخصية بينك وبين الله. لا يوجد "إجراء رسمي" أو تسجيل حكومي داخل التطبيق.',
      'di_intro_btn_start': 'أريد أن أقول الشهادتين الآن',
      'di_intro_btn_questions': 'لدي أسئلة قبل ذلك',
      'di_learn_shahada_ar':
          'أشهد أن لا إله إلا الله\nوأشهد أن محمداً رسول الله',
      'di_learn_btn_next': 'متابعة',
      'di_learn_btn_contact': 'تواصل مع داعية',
      'di_readiness_title': 'قبل التأكيد',
      'di_readiness_check_1': 'أفهم معنى الشهادتين',
      'di_readiness_check_2': 'أقولها باختياري وقناعة',
      'di_readiness_check_3': 'قلتهما الآن بلساني',
      'di_btn_confirm': 'أكملت الشهادتين',
      'di_confirmed_official_note':
          'هذا تأكيد شخصي داخل التطبيق وليس تسجيلًا رسميًا لأي جهة.',
      'di_undo_btn': 'ضغطت بالخطأ / تراجع عن هذا التأكيد',
      'di_contact_privacy_note':
          'سنستخدم وسيلة التواصل التي تختارها فقط للرد على سؤالك.',
      'shahada_transliteration': '', // Not needed for Arabic, or empty
      'module_coming_soon': 'وحدة {0} - قريباً',
      'email_subject_inquiry': 'استفسار',
      'di_exit_confirm_title': 'هل تريد الخروج؟',
      'di_exit_confirm_body': 'ستفقد تقدمك في هذه الخطوة.',
      'di_exit_confirm_stay': 'البقاء',
      'di_exit_confirm_leave': 'الخروج',
      // Audio Player Redesign Strings
      'continue_reading': 'متابعة القراءة',
      'continue_listening': 'متابعة الاستماع',
      'transcript_title': 'النص',
      'table_of_contents': 'الفهرس',
      'search_in_text': 'بحث في النص',
      'reading_mode': 'وضع القراءة',
      'font_size_increase': 'تكبير الخط',
      'font_size_decrease': 'تصغير الخط',
      'speed_setting': 'السرعة',
      'playback_speed': 'سرعة التشغيل',
      'rewind_10s': 'تأخير 10 ثوانٍ',
      'forward_10s': 'تقديم 10 ثوانٍ',
      'elapsed_time': 'الوقت المنقضي',
      'remaining_time': 'الوقت المتبقي',
      'progress_percent': '{0}% مكتمل',
      'resume_at_time': 'استئناف عند {0}',
      'reset_reading_progress': 'إعادة تعيين تقدم القراءة',
      'reset_listening_progress': 'إعادة تعيين تقدم الاستماع',
      'reset_progress_confirm_title': 'تأكيد إعادة التعيين',
      'reset_reading_confirm_body': 'هل تريد حذف موضع القراءة المحفوظ؟',
      'reset_listening_confirm_body': 'هل تريد حذف موضع الاستماع المحفوظ؟',
      'audio_downloading': 'جاري تنزيل الصوت بلغة {0}...',
      'audio_offline_unavailable': 'الصوت غير متوفر دون اتصال',
      'audio_settings': 'إعدادات الصوت',
      'audio_language': 'لغة الصوت',
      'progress_management': 'إدارة التقدم',
      'compact_mode': 'وضع مضغوط',
      'comfortable_mode': 'وضع مريح',
      'search_results': '{0} نتيجة',
      'previous_result': 'النتيجة السابقة',
      'next_result': 'النتيجة التالية',
      // Sprint A — new strings
      'share_app_message': 'شاركوا رسالة الإسلام مع من تحبون',
      'offline_first_run_title': 'لا يوجد محتوى محلي',
      'offline_first_run_body':
          'تعذّر تحميل المحتوى. تأكد من اتصالك بالإنترنت ثم أعد المحاولة.',
      'home_loading_content': 'جاري تحميل المحتوى...',
      'sync_toggle_on': 'إيقاف تزامن النص',
      'sync_toggle_off': 'تفعيل تزامن النص',
      'follow_toggle_on': 'إيقاف اتّباع الصوت',
      'follow_toggle_off': 'تفعيل اتّباع الصوت',
      'audio_progress_bar': 'شريط تقدم الصوت',
      'audio_player_error': 'تعذّر تحميل الصوت، حاول مجدداً',
      'message_not_found': 'المحتوى غير متاح حالياً',
      'message_not_found_body':
          'ربما تُحدِّث المحتوى، يرجى العودة للصفحة الرئيسية.',
    },
    'en': {
      'appTitle': 'Message of Islam',
      'settings': 'Settings',
      'appLanguage': 'App Language',
      'contentLanguage': 'Content Language',
      'drawer_continue': 'Continue Reading',
      'drawer_bookmarks': 'Bookmarks',
      'drawer_sync': 'Update Content',
      'drawer_syncing': 'Updating...',
      'drawer_about': 'About',
      'drawer_privacy': 'Privacy Policy',
      'drawer_contact': 'Contact Us',
      'drawer_share': 'Share App',
      'drawer_rate': 'Rate App',
      'drawer_dark_mode': 'Dark Mode',
      'drawer_light_mode': 'Light Mode',
      'theme_system': 'System Theme',
      'dark_mode_subtitle': 'Change app appearance',
      'settings_label': 'Audio Settings',
      'quick_actions_header': 'Quick Actions',
      'about_app_header': 'About App',
      'about_app_name': 'Message of Islam',
      'about_legalese': 'All rights reserved © 2025',
      'ready_offline': 'Works Offline',
      'version': 'Version',
      'dialog_language': 'Choose Language',
      'dialog_privacy': 'Privacy Policy',
      'privacy_policy_content':
          'The privacy policy for this app is simple:\n\n1. We do not collect any personal data.\n2. All data (like bookmarks) is stored locally on your device.\n3. The app does not share any information with third parties.\n\nIf you have any questions, please contact us.',
      'dialog_ok': 'OK',
      'sync_success': 'Content Updated Successfully',
      'sync_fail': 'Update Failed',
      'theme_switched': 'Theme Changed',
      'lang_switched': 'Language Changed to',
      'no_read_history': 'No reading history found',
      'no_sections': 'No sections found',
      'loading_error': 'Error loading content',
      'retry': 'Retry',
      'no_content': 'No content',
      'all': 'All',
      'empty_section': 'No content in this section',
      'no_translation': 'No translation available',
      'declare_islam': 'Declare Islam',
      'islam_step': 'A blessed step towards the light',
      'contact_daiyah': 'Contact a Daiyah',
      'daiyah_desc': 'We are here to answer your questions',
      'content_header': 'Content',
      'bookmark_saved': 'Position saved',
      'flip_page_hint': 'Flip page to read more',
      'scroll_hint': 'Swipe down to read',
      'back': 'Back',
      'chapter': 'Chapter',
      'no_bookmarks_hint':
          'No bookmarks saved yet\nAdd one from the reading page',
      'bookmarks_title': 'Bookmarks',
      'bookmark_deleted': 'Bookmark deleted',
      'bookmark_default_title': 'Bookmark',
      'time_now': 'Just now',
      'time_min_ago': '{0}m ago',
      'time_hour_ago': '{0}h ago',
      'time_day_ago': '{0}d ago',
      'chapters_title': 'Chapters',
      'appearance_title': 'Appearance',
      'view_scroll': 'Scroll',
      'view_pager': 'Paged',
      'text_settings': 'Text',
      'font_size': 'Font Size',
      'line_height': 'Line Spacing',
      'language_settings': 'Language',
      'default_content_language': 'Default Content Language',
      'not_set': 'Not set',
      'use_default_language': 'Use Default Language',
      'language_picker_title': 'Choose language for this message',
      'language_picker_subtitle': 'This applies to this message only',
      'custom_override_badge': 'Custom',
      'default_label': 'Default',
      'generic_error': 'Error: {0}',
      'message_default_title': 'Message #{0}',
      'delete_file_title': 'Delete File?',
      'delete_file_confirmation': 'Delete audio file for "{0}"?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'deleted_success': 'Deleted successfully',
      'contact_daiyah_title': 'Contact Daiyah',
      'we_here_help': 'We are here to help',
      'contact_desc':
          'You can contact us via WhatsApp or Email for any questions.\n\nNote: We reply based on availability and strive to respond as soon as possible.',
      'whatsapp': 'WhatsApp',
      'whatsapp_subtitle': 'Direct message chat',
      'email': 'Email',
      'email_subtitle': 'Send us a detailed inquiry',
      'launch_error': 'Could not launch: {0}',
      'data_error': 'Data error: {0}',
      'welcome_header': 'Welcome...',
      'islam_definition':
          'Islam is submission to God through Monotheism and obedience.\nEntering Islam does not require any formal procedures, only pronouncing the Testimony of Faith with a convinced heart.',
      'shahada_arabic': 'أشهد أن لا إله إلا الله\nوأشهد أن محمداً رسول الله',
      'shahada_english':
          'I bear witness that there is no god but Allah,\nand I bear witness that Muhammad is the Messenger of Allah.',
      'declare_button': 'I declare entering Islam',
      'declare_disclaimer':
          'This button does not record any data, it is just a personal declaration from you.',
      'congrats_header': 'Congratulations!',
      'congrats_body':
          'You have taken the most important step in your life.\nWe ask God to strengthen you and enlighten your heart.',
      'whats_next': 'What\'s next?',
      'next_step_1': 'Start learning Prayer',
      'next_step_2': 'Read the Quran and contemplate its meanings',
      'next_step_3': 'Contact us for any questions',
      'messages_load_error': 'Error loading messages.\n{0}',
      'no_global_bookmarks': 'No bookmarks yet',
      'no_bookmarks_found': 'No bookmarks found for existing messages',
      'default_excerpt': 'Excerpt',
      'audio_language_label': 'Audio Language:',
      'audio_loading_error': 'Error loading audio: {0}',
      'changing_language_audio': 'Changing language and playing audio...',
      'audio_download_error': 'Could not load audio',
      'speed_label': 'Speed\n{0}x',
      'download_button': 'Download',
      'file_already_downloaded': 'File already downloaded',
      'downloading_progress': 'Downloading...',
      'download_completed': 'Download completed',
      'download_failed': 'Download failed: {0}',
      'no_audio_source': 'No audio source',
      'audio_playback_error': 'Audio playback failed',
      'local_audio_error': 'Failed to play local file: {0}',
      'select_content_language': 'Select Content Language',
      'content_language_desc':
          'You can read and listen to messages in multiple languages',
      'confirm_continue': 'Confirm & Continue',
      'change_language_anytime':
          'You can change the language anytime from within each message',
      'section_meaning': 'The Purpose of Existence',
      'section_islam': 'Introduction to Islam',
      'section_logic': 'Logical Dialogues',
      'section_god': 'Knowing Allah',
      'section_prophet': 'Prophet Muhammad PBUH',
      'section_quran': 'About the Holy Quran',
      'section_ready': 'Ready for Islam',
      'section_guidance': 'New Muslim Guide',
      'read': 'Read',
      'listen': 'Listen',
      'lang_ar': 'Arabic',
      'lang_en': 'English',
      'lang_fr': 'French',
      'lang_ur': 'Urdu',
      'lang_fa': 'Persian',
      'lang_id': 'Indonesian',
      'lang_sw': 'Swahili',
      'lang_am': 'Amharic',
      'lang_hi': 'Hindi',
      'lang_tl': 'Tagalog',
      'lang_bn': 'Bengali',
      'lang_tr': 'Turkish',
      'lang_ru': 'Russian',
      'lang_zh': 'Chinese',
      'lang_es': 'Spanish',
      'lang_pt': 'Portuguese',
      'lang_de': 'German',
      'lang_ja': 'Japanese',
      'lang_ko': 'Korean',
      'lang_it': 'Italian',
      'lang_nl': 'Dutch',
      'lang_pl': 'Polish',
      'lang_vi': 'Vietnamese',
      'lang_th': 'Thai',
      'lang_ms': 'Malay',
      'lang_he': 'Hebrew',
      'lang_el': 'Greek',
      'lang_cs': 'Czech',
      'lang_ro': 'Romanian',
      'lang_hu': 'Hungarian',
      'select_language': 'Select Language',
      'search_language': 'Search languages...',
      'no_language_found': 'No language found',
      // Contact Us
      'contact_us_title': 'Contact Us',
      'contact_us_subtitle': 'We are here to help',
      'contact_us_description':
          'Share your questions, suggestions, or any issues you\'re facing',
      'contact_category': 'Message Type',
      'contact_message': 'Your Message',
      'contact_message_hint': 'Write your message here...',
      'contact_message_required': 'Please write a message',
      'contact_message_too_short':
          'Message is too short (at least 10 characters)',
      'contact_email': 'Email',
      'contact_email_hint': 'For follow-up',
      'contact_email_invalid': 'Invalid email address',
      'contact_submit': 'Submit',
      'contact_disclaimer':
          'We\'ll get back to you as soon as possible. Thank you for reaching out!',
      'contact_sent_success': 'Message sent successfully',
      'contact_saved_offline': 'Message saved and will be sent when online',
      'optional': 'Optional',
      'category_question': 'Question',
      'category_feedback': 'Feedback',
      'category_bug_report': 'Bug Report',
      'category_feature_request': 'Feature Request',
      'category_other': 'Other',
      // Content Reporting
      'report_content_title': 'Report Issue',
      'report_content_subtitle': 'Help us improve content quality',
      'report_type': 'Issue Type',
      'report_comment': 'Additional Details',
      'report_comment_hint': 'You can add details...',
      'report_submit': 'Submit Report',
      'report_info': 'Message and language info will be sent automatically',
      'report_sent_success': 'Report sent successfully',
      'report_saved_offline': 'Report saved and will be sent when online',
      'report_translation_error': 'Translation Error',
      'report_missing_audio': 'Missing Audio',
      'report_technical_issue': 'Technical Issue',
      'report_inappropriate_content': 'Inappropriate Content',
      'report_other': 'Other',
      'onboarding_welcome_title': 'Welcome to Message of Islam',
      'onboarding_welcome_desc':
          'Selected content to introduce Islam: reading and listening.',
      'onboarding_language_title': 'Multilingual Content',
      'onboarding_language_desc':
          'Easily choose the language for each content item.',
      'onboarding_audio_title': 'Comfortable Reading',
      'onboarding_audio_desc':
          'Control font size, line spacing, and comfortable reading mode.',
      'onboarding_get_started': 'Start Now',
      'onboarding_next': 'Next',
      'onboarding_skip': 'Skip',
      'onboarding_previous': 'Previous',
      'onboarding_step_counter': '{current}/{total}',
      'listen_action': 'Listen',
      'audio_unavailable_label': 'Audio unavailable for this language',
      'change_language_action': 'Change Language',
      'audio_next_track': 'Next',
      'audio_previous_track': 'Previous',
      'audio_loading_progress': 'Loading audio...',
      'audio_play_button': 'Play {0}',
      'audio_pause_button': 'Pause',
      'audio_loading': 'Loading',
      'audio_speed_control': 'Speed control, current {0}',
      // Declare Islam Feature
      'di_intro_meaning_title': 'The Meaning of Shahada',
      'di_intro_meaning_body':
          'It is the key to Islam: to testify that there is no god but Allah and that Muhammad is the Messenger of Allah.',
      'di_intro_note_title': 'Important Note',
      'di_intro_note_body':
          'This is a personal step between you and God. There is no "official procedure" or government registration involved in this app.',
      'di_intro_btn_start': 'I want to say the Shahada now',
      'di_intro_btn_questions': 'I have questions first',
      'di_learn_shahada_ar':
          'أشهد أن لا إله إلا الله\nوأشهد أن محمداً رسول الله',
      'di_learn_btn_next': 'Continue',
      'di_learn_btn_contact': 'Contact a Daiyah',
      'di_readiness_title': 'Before Confirming',
      'di_readiness_check_1': 'I understand the meaning of Shahada',
      'di_readiness_check_2': 'I say it by my own choice and conviction',
      'di_readiness_check_3': 'I have said it now with my tongue',
      'di_btn_confirm': 'I have completed the Shahada',
      'di_confirmed_official_note':
          'This is a personal confirmation within the app, not an official registration with any authority.',
      'di_undo_btn': 'Pressed by mistake / Undo this confirmation',
      'di_contact_privacy_note':
          'We will use your chosen contact method only to reply to your question.',
      'shahada_transliteration':
          'Ash-hadu an la ilaha illa Allah,\nwa ash-hadu anna Muhammadan rasul Allah',
      'module_coming_soon': '{0} Module - Coming Soon',
      'email_subject_inquiry': 'Inquiry',
      'di_exit_confirm_title': 'Leave this step?',
      'di_exit_confirm_body': 'You will lose your progress.',
      'di_exit_confirm_stay': 'Stay',
      'di_exit_confirm_leave': 'Leave',
      // Audio Player Redesign Strings
      'continue_reading': 'Continue Reading',
      'continue_listening': 'Continue Listening',
      'transcript_title': 'Transcript',
      'table_of_contents': 'Table of Contents',
      'search_in_text': 'Search in text',
      'reading_mode': 'Reading Mode',
      'font_size_increase': 'Increase font size',
      'font_size_decrease': 'Decrease font size',
      'speed_setting': 'Speed',
      'playback_speed': 'Playback Speed',
      'rewind_10s': 'Rewind 10 seconds',
      'forward_10s': 'Forward 10 seconds',
      'elapsed_time': 'Elapsed Time',
      'remaining_time': 'Remaining Time',
      'progress_percent': '{0}% complete',
      'resume_at_time': 'Resume at {0}',
      'reset_reading_progress': 'Reset Reading Progress',
      'reset_listening_progress': 'Reset Listening Progress',
      'reset_progress_confirm_title': 'Confirm Reset',
      'reset_reading_confirm_body': 'Delete saved reading position?',
      'reset_listening_confirm_body': 'Delete saved listening position?',
      'audio_downloading': 'Downloading {0} audio...',
      'audio_offline_unavailable': 'Audio not available offline',
      'audio_settings': 'Audio Settings',
      'audio_language': 'Audio Language',
      'progress_management': 'Progress Management',
      'compact_mode': 'Compact Mode',
      'comfortable_mode': 'Comfortable Mode',
      'search_results': '{0} results',
      'previous_result': 'Previous result',
      'next_result': 'Next result',
      // Sprint A — new strings
      'share_app_message': 'Share Message of Islam with someone you care about',
      'offline_first_run_title': 'No local content',
      'offline_first_run_body':
          'Could not load content. Please check your connection and try again.',
      'home_loading_content': 'Loading content...',
      'sync_toggle_on': 'Disable text sync',
      'sync_toggle_off': 'Enable text sync',
      'follow_toggle_on': 'Disable follow audio',
      'follow_toggle_off': 'Enable follow audio',
      'audio_progress_bar': 'Audio progress bar',
      'audio_player_error': 'Could not load audio. Please try again.',
      'message_not_found': 'Content not available',
      'message_not_found_body':
          'This content may be updating. Please go back and try again.',
    },
    'fr': {
      'theme_system': 'Thème du système',
      'settings_label': 'Paramètres audio',
    },
  };

  static String of(BuildContext context, String key) {
    // If context is not available or localizations not fully set up, fallback safely
    try {
      final locale = Localizations.localeOf(context);
      return _values[locale.languageCode]?[key] ?? _values['ar']![key] ?? key;
    } catch (_) {
      return _values['ar']![key] ?? key;
    }
  }

  // Helper for non-context usage if needed (using code directly)
  static String get(String code, String key) {
    return _values[code]?[key] ?? _values['ar']![key] ?? key;
  }
}
