import 'package:drift/drift.dart';

/// Table to store offline analytics events.
@DataClassName('AnalyticsQueueEntry')
class AnalyticsEventQueue extends Table {
  /// Unique ID generated by the client (UUID).
  TextColumn get clientEventId => text()();

  /// ISO 8601 UTC timestamp of when the event occurred.
  TextColumn get occurredAt => text()();

  /// The event name (e.g., 'screen_view').
  TextColumn get eventName => text()();

  /// Full JSON payload of the event.
  TextColumn get payloadJson => text()();

  /// Number of upload attempts.
  IntColumn get attempts => integer().withDefault(const Constant(0))();

  /// Next retry timestamp (Unix ms). Null means ready to send immediately.
  IntColumn get nextRetryAt => integer().nullable()();

  /// When this row was created (Unix ms).
  IntColumn get createdAt => integer()();

  @override
  Set<Column> get primaryKey => {clientEventId};
}
